// <auto-generated />
namespace HxAntenna.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class add_models_for_pim : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_models_for_pim));
        
        string IMigrationMetadata.Id
        {
            get { return "201512011717271_add_models_for_pim"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
